export default {
  expo: {
    name: 'BandChat',
    slug: 'bandchat',
    scheme: 'bandchat',
    version: '1.03.78',
    orientation: 'portrait',
    icon: './assets/icon.png',
    userInterfaceStyle: 'dark',
    description: 'Real-time communication and management app for bands. Channels, messaging, song management, setlists, calendar, and more.',
    splash: {
      image: './assets/splash-icon.png',
      resizeMode: 'contain',
      backgroundColor: '#1f2937',
    },
    ios: {
      supportsTablet: false,
      bundleIdentifier: 'com.bandchat.mobile',
      buildNumber: '10378',
      infoPlist: {
        NSCameraUsageDescription: 'BandChat needs camera access to take photos for your profile and messages.',
        NSPhotoLibraryUsageDescription: 'BandChat needs photo library access to share images in messages and set your profile picture.',
        NSPhotoLibraryAddUsageDescription: 'BandChat needs permission to save images to your photo library.',
        NSMicrophoneUsageDescription: 'BandChat needs microphone access to record audio for band recordings.',
        NSCalendarsUsageDescription: 'BandChat can add gigs and rehearsals to your device calendar.',
        NSCalendarsFullAccessUsageDescription: 'BandChat can add gigs and rehearsals to your device calendar.',
        UIBackgroundModes: ['remote-notification'],
      },
    },
    android: {
      package: 'com.bandchat.mobile',
      versionCode: 10378,
      adaptiveIcon: {
        backgroundColor: '#1f2937',
        foregroundImage: './assets/android-icon-foreground.png',
        backgroundImage: './assets/android-icon-background.png',
        monochromeImage: './assets/android-icon-monochrome.png',
      },
      permissions: [
        'CAMERA',
        'READ_MEDIA_IMAGES',
        'READ_MEDIA_VIDEO',
        'READ_MEDIA_AUDIO',
        'RECORD_AUDIO',
        'READ_CALENDAR',
        'WRITE_CALENDAR',
        'VIBRATE',
        'INTERNET',
        'ACCESS_NETWORK_STATE',
      ],
    },
    web: {
      favicon: './assets/favicon.png',
    },
    extra: {
      apiUrl: process.env.EXPO_PUBLIC_API_URL || 'http://localhost:3001/api',
      socketUrl: process.env.EXPO_PUBLIC_SOCKET_URL || 'http://localhost:3001',
    },
    plugins: [
      'expo-secure-store',
      'expo-asset',
      'expo-font',
      'expo-calendar',
      'expo-image-picker',
      'expo-notifications',
    ],
  },
};
