/**
 * Website deployment service — manages GitHub + Vercel integration
 * for band websites deployed at bandname.bandchat.app.
 */

import crypto from 'crypto';
import prisma from '../lib/prisma.js';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const VERCEL_TOKEN = process.env.VERCEL_TOKEN;
const VERCEL_TEAM_ID = process.env.VERCEL_TEAM_ID;
const WEBSITE_TEMPLATE_REPO = process.env.WEBSITE_TEMPLATE_REPO || 'bandchat-website-template';
const WEBSITE_GITHUB_ORG = process.env.WEBSITE_GITHUB_ORG || 'bandchat-sites';

function githubHeaders() {
  return {
    Authorization: `Bearer ${GITHUB_TOKEN}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
}

function vercelHeaders() {
  return {
    Authorization: `Bearer ${VERCEL_TOKEN}`,
    'Content-Type': 'application/json',
  };
}

function vercelTeamParam() {
  return VERCEL_TEAM_ID ? `?teamId=${VERCEL_TEAM_ID}` : '';
}

/**
 * Create a new repo from the template for this band.
 * Uses GitHub's "create repo from template" API (not fork — forks can't target the same org).
 */
export async function forkTemplate(bandSlug) {
  const repoName = `bandchat-${bandSlug}`;
  const res = await fetch(`https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${WEBSITE_TEMPLATE_REPO}/generate`, {
    method: 'POST',
    headers: {
      ...githubHeaders(),
      Accept: 'application/vnd.github.baptiste-preview+json',
    },
    body: JSON.stringify({
      owner: WEBSITE_GITHUB_ORG,
      name: repoName,
      private: false,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`GitHub repo creation failed: ${err.message || res.statusText}`);
  }

  return repoName;
}

/**
 * Write site.config.js to the forked repo via GitHub Contents API.
 */
export async function writeSiteConfig(repoName, config) {
  const path = 'site.config.js';
  const content = `// Auto-generated by BandChat — do not edit manually\nexport default ${JSON.stringify(config, null, 2)};\n`;
  const encoded = Buffer.from(content).toString('base64');

  // Check if file exists (to get sha for update)
  let sha;
  const getRes = await fetch(`https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${repoName}/contents/${path}`, {
    headers: githubHeaders(),
  });
  if (getRes.ok) {
    const existing = await getRes.json();
    sha = existing.sha;
  }

  const body = {
    message: 'Update site config from BandChat',
    content: encoded,
    ...(sha && { sha }),
  };

  const res = await fetch(`https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${repoName}/contents/${path}`, {
    method: 'PUT',
    headers: githubHeaders(),
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`GitHub config write failed: ${err.message || res.statusText}`);
  }
}

/**
 * Create a Vercel project linked to the GitHub repo.
 */
export async function createVercelProject(repoName, bandSlug) {
  const res = await fetch(`https://api.vercel.com/v10/projects${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify({
      name: `bandchat-${bandSlug}`,
      framework: 'vite',
      gitRepository: {
        type: 'github',
        repo: `${WEBSITE_GITHUB_ORG}/${repoName}`,
      },
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Vercel project creation failed: ${err.error?.message || res.statusText}`);
  }

  const project = await res.json();
  return project.id;
}

/**
 * Set environment variables on the Vercel project.
 */
export async function setVercelEnvVars(projectId, vars) {
  const envVars = Object.entries(vars).map(([key, value]) => ({
    key,
    value: String(value),
    target: ['production', 'preview'],
    type: 'encrypted',
  }));

  const res = await fetch(`https://api.vercel.com/v10/projects/${projectId}/env${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify(envVars),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Vercel env vars failed: ${err.error?.message || res.statusText}`);
  }
}

/**
 * Add a custom domain to the Vercel project.
 */
export async function addVercelDomain(projectId, domain) {
  const res = await fetch(`https://api.vercel.com/v10/projects/${projectId}/domains${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify({ name: domain }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Vercel domain failed: ${err.error?.message || res.statusText}`);
  }
}

/**
 * Create a deploy hook URL for the Vercel project (used for auto-rebuilds).
 */
export async function createDeployHook(projectId) {
  const res = await fetch(`https://api.vercel.com/v10/projects/${projectId}/deploy-hooks${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify({
      name: 'bandchat-sync',
      ref: 'main',
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Deploy hook creation failed: ${err.error?.message || res.statusText}`);
  }

  const data = await res.json();
  return data.url;
}

/**
 * Trigger a deploy via the deploy hook URL (fire-and-forget POST).
 */
export async function triggerDeploy(deployHookUrl) {
  if (!deployHookUrl) return;
  try {
    await fetch(deployHookUrl, { method: 'POST' });
  } catch {
    // Fire-and-forget — don't throw
    console.error('Website deploy hook trigger failed');
  }
}

/**
 * Delete the Vercel project.
 */
export async function deleteVercelProject(projectId) {
  const res = await fetch(`https://api.vercel.com/v10/projects/${projectId}${vercelTeamParam()}`, {
    method: 'DELETE',
    headers: vercelHeaders(),
  });

  if (!res.ok && res.status !== 404) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Vercel project deletion failed: ${err.error?.message || res.statusText}`);
  }
}

/**
 * Delete the GitHub repo for this band's website.
 */
export async function deleteGithubRepo(repoName) {
  const res = await fetch(`https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${repoName}`, {
    method: 'DELETE',
    headers: githubHeaders(),
  });

  if (!res.ok && res.status !== 404) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`GitHub repo deletion failed: ${err.message || res.statusText}`);
  }
}

/**
 * Generate a scoped API token for the website to fetch band data.
 * Returns the plaintext token (stored hashed in DB).
 */
export async function generateApiToken(workspaceId) {
  const plaintext = crypto.randomBytes(32).toString('hex');
  const hashed = crypto.createHash('sha256').update(plaintext).digest('hex');

  // Delete any existing tokens for this workspace
  await prisma.websiteApiToken.deleteMany({ where: { workspaceId } });

  await prisma.websiteApiToken.create({
    data: {
      token: hashed,
      workspaceId,
    },
  });

  return plaintext;
}

/**
 * Verify a website API token. Returns workspaceId if valid, null otherwise.
 */
export async function verifyApiToken(plaintext) {
  if (!plaintext) return null;
  const hashed = crypto.createHash('sha256').update(plaintext).digest('hex');
  const record = await prisma.websiteApiToken.findUnique({ where: { token: hashed } });
  return record ? record.workspaceId : null;
}

/**
 * Debounce map: workspaceId → timeout handle.
 * Prevents deploy hook storms when many mutations happen in quick succession
 * (e.g. bulk song import). Waits 5 minutes after the last change before triggering.
 */
const SYNC_DEBOUNCE_MS = 5 * 60 * 1000; // 5 minutes
const syncTimers = new Map();

/**
 * Trigger a website rebuild if the workspace has a website enabled.
 * Debounced — waits 5 minutes after the last call before firing.
 * Fire-and-forget — safe to call from any route.
 */
export function triggerWebsiteSync(workspaceId) {
  // Clear any pending timer for this workspace
  const existing = syncTimers.get(workspaceId);
  if (existing) clearTimeout(existing);

  const timer = setTimeout(async () => {
    syncTimers.delete(workspaceId);
    try {
      const workspace = await prisma.workspace.findUnique({
        where: { id: workspaceId },
        select: { websiteEnabled: true, websiteDeployHook: true },
      });
      if (workspace?.websiteEnabled && workspace.websiteDeployHook) {
        triggerDeploy(workspace.websiteDeployHook);
      }
    } catch {
      // Best effort — don't crash
    }
  }, SYNC_DEBOUNCE_MS);

  syncTimers.set(workspaceId, timer);
}
