/**
 * Website deployment service — manages GitHub + Vercel integration
 * for band websites deployed at bandname.bandchat.app.
 */

import crypto from 'crypto';
import prisma from '../lib/prisma.js';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const VERCEL_TOKEN = process.env.VERCEL_TOKEN;
const VERCEL_TEAM_ID = process.env.VERCEL_TEAM_ID;
const WEBSITE_TEMPLATE_REPO = process.env.WEBSITE_TEMPLATE_REPO || 'bandchat-website-template';
const WEBSITE_GITHUB_ORG = process.env.WEBSITE_GITHUB_ORG || 'bandchat-sites';

function githubHeaders() {
  return {
    Authorization: `Bearer ${GITHUB_TOKEN}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
}

function vercelHeaders() {
  return {
    Authorization: `Bearer ${VERCEL_TOKEN}`,
    'Content-Type': 'application/json',
  };
}

function vercelTeamParam() {
  return VERCEL_TEAM_ID ? `?teamId=${VERCEL_TEAM_ID}` : '';
}

/**
 * Create a new repo from the template for this band.
 * Uses GitHub's "create repo from template" API (not fork — forks can't target the same org).
 */
export async function forkTemplate(bandSlug) {
  const repoName = `bandchat-${bandSlug}`;
  const res = await fetch(`https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${WEBSITE_TEMPLATE_REPO}/generate`, {
    method: 'POST',
    headers: {
      ...githubHeaders(),
      Accept: 'application/vnd.github.baptiste-preview+json',
    },
    body: JSON.stringify({
      owner: WEBSITE_GITHUB_ORG,
      name: repoName,
      private: true,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`GitHub repo creation failed: ${err.message || res.statusText}`);
  }

  return repoName;
}

/**
 * Write site.config.js to the repo via GitHub Contents API.
 * Retries if the repo isn't ready yet (template API creates repos asynchronously).
 */
export async function writeSiteConfig(repoName, config) {
  const path = 'site.config.js';
  const content = `// Auto-generated by BandChat — do not edit manually\nexport default ${JSON.stringify(config, null, 2)};\n`;
  const encoded = Buffer.from(content).toString('base64');

  // Wait for repo to be ready (template API is async)
  let sha;
  for (let attempt = 0; attempt < 10; attempt++) {
    const getRes = await fetch(`https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${repoName}/contents/${path}`, {
      headers: githubHeaders(),
    });
    if (getRes.ok) {
      const existing = await getRes.json();
      sha = existing.sha;
      break;
    }
    // Repo not ready yet — wait and retry
    console.log(`Waiting for repo to be ready (attempt ${attempt + 1}/10)...`);
    await new Promise(r => setTimeout(r, 3000));
  }

  if (!sha) {
    throw new Error('GitHub repo not ready after 30s — site.config.js not found');
  }

  const body = {
    message: 'Update site config from BandChat',
    content: encoded,
    sha,
  };

  const res = await fetch(`https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${repoName}/contents/${path}`, {
    method: 'PUT',
    headers: githubHeaders(),
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`GitHub config write failed: ${err.message || res.statusText}`);
  }
}

/**
 * Read the template version (from its package.json) so the UI can show a
 * "Upgrade available: vX.Y.Z" hint when the band's repo is on an older one.
 */
export async function getTemplateVersion() {
  const res = await fetch(
    `https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${WEBSITE_TEMPLATE_REPO}/contents/package.json`,
    { headers: githubHeaders() }
  );
  if (!res.ok) return null;
  const data = await res.json();
  try {
    const pkg = JSON.parse(Buffer.from(data.content, 'base64').toString('utf-8'));
    return pkg.version || null;
  } catch {
    return null;
  }
}

/**
 * Read the band's repo template version (from its package.json) — used to
 * compare against `getTemplateVersion()` for the UI's "upgrade available" hint.
 */
export async function getBandRepoTemplateVersion(repoName) {
  const res = await fetch(
    `https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${repoName}/contents/package.json`,
    { headers: githubHeaders() }
  );
  if (!res.ok) return null;
  const data = await res.json();
  try {
    const pkg = JSON.parse(Buffer.from(data.content, 'base64').toString('utf-8'));
    return pkg.version || null;
  } catch {
    return null;
  }
}

/**
 * Band-specific paths that must NOT be overwritten when copying template
 * source into a band's repo. Their `site.config.js` carries the band's
 * identity, `public/data/` is synced JSON, `public/images/logos+site/` is
 * the band's uploaded assets, etc. Everything else is template source code
 * that should track the upstream template repo.
 */
const BAND_SPECIFIC_PATHS = [
  'site.config.js',
  'package-lock.json',
  'CHANGELOG.md',
  '.env',
  '.env.local',
  '.env.example',
  'backups/',
];

const BAND_SPECIFIC_PREFIXES = [
  'public/data/',
  'public/images/logos/',
  'public/images/site/',
  'public/images/members/',
  'public/images/gigs/',
  'backups/',
  'node_modules/',
  'dist/',
  '.next/',
];

function isBandSpecific(path) {
  if (BAND_SPECIFIC_PATHS.includes(path)) return true;
  return BAND_SPECIFIC_PREFIXES.some(prefix => path.startsWith(prefix));
}

/**
 * Pull the latest template source into a band's existing repo.
 *
 * Each band's repo is a one-time clone from the template (via GitHub's
 * "generate from template" API), so it has no Git relationship to upstream.
 * To get template improvements (like new components, bug fixes, etc.) into
 * an existing band site, we have to manually copy each file via the GitHub
 * Contents API, preserving the band's per-site files (site.config.js,
 * uploaded images, synced data).
 *
 * Returns `{ filesUpdated, filesCreated, filesSkipped }` summary.
 *
 * Caller should trigger a sync/deploy after this so Vercel rebuilds with
 * the new template source.
 */
export async function upgradeTemplate(bandRepoName) {
  const owner = WEBSITE_GITHUB_ORG;

  // 1. Get the template repo's HEAD tree (recursive — every file at HEAD).
  const refRes = await fetch(
    `https://api.github.com/repos/${owner}/${WEBSITE_TEMPLATE_REPO}/git/refs/heads/master`,
    { headers: githubHeaders() }
  );
  if (!refRes.ok) {
    // Some template repos use 'main' instead of 'master'
    const mainRes = await fetch(
      `https://api.github.com/repos/${owner}/${WEBSITE_TEMPLATE_REPO}/git/refs/heads/main`,
      { headers: githubHeaders() }
    );
    if (!mainRes.ok) {
      throw new Error('Could not resolve template repo HEAD ref (tried master + main)');
    }
    refRes.body = mainRes.body;
    Object.assign(refRes, { ok: true });
  }
  const refData = refRes.ok ? await refRes.json() : null;
  const headSha = refData?.object?.sha;
  if (!headSha) throw new Error('Template repo HEAD ref returned no SHA');

  const commitRes = await fetch(
    `https://api.github.com/repos/${owner}/${WEBSITE_TEMPLATE_REPO}/git/commits/${headSha}`,
    { headers: githubHeaders() }
  );
  if (!commitRes.ok) throw new Error('Failed to fetch template HEAD commit');
  const { tree: { sha: treeSha } } = await commitRes.json();

  const treeRes = await fetch(
    `https://api.github.com/repos/${owner}/${WEBSITE_TEMPLATE_REPO}/git/trees/${treeSha}?recursive=1`,
    { headers: githubHeaders() }
  );
  if (!treeRes.ok) throw new Error('Failed to fetch template tree');
  const { tree, truncated } = await treeRes.json();
  if (truncated) {
    // The repo has more files than GitHub returns in one shot. We'd need
    // pagination via the Git Trees API. Unlikely for a website template but
    // worth being explicit if it ever happens.
    console.warn('[upgradeTemplate] template tree was truncated — some files may not be copied');
  }

  // 2. Filter to copyable files (template source only; skip band-specific).
  const filesToCopy = tree.filter(item => item.type === 'blob' && !isBandSpecific(item.path));

  // 3. For each, fetch content from template and write to band repo. We use
  // the Contents API per-file (one PUT each, creates a commit) for simplicity
  // — could batch via Git Tree API but the latency win isn't worth the
  // complexity for ~50 files. Skip the write if content is byte-identical.
  let filesUpdated = 0;
  let filesCreated = 0;
  let filesSkipped = 0;

  for (const file of filesToCopy) {
    // Fetch template blob (base64-encoded)
    const blobRes = await fetch(
      `https://api.github.com/repos/${owner}/${WEBSITE_TEMPLATE_REPO}/git/blobs/${file.sha}`,
      { headers: githubHeaders() }
    );
    if (!blobRes.ok) {
      console.warn(`[upgradeTemplate] failed to fetch template blob ${file.path}`);
      continue;
    }
    const blob = await blobRes.json();
    const templateContent = blob.content; // base64

    // Check what (if anything) the band repo has at this path. We need the
    // current SHA to update (PUT requires it for existing files); 404 means
    // we'll create the file fresh.
    const existingRes = await fetch(
      `https://api.github.com/repos/${owner}/${bandRepoName}/contents/${encodeURIComponent(file.path)}`,
      { headers: githubHeaders() }
    );
    let existingSha = null;
    let existingContent = null;
    if (existingRes.ok) {
      const existing = await existingRes.json();
      existingSha = existing.sha;
      existingContent = existing.content?.replace(/\n/g, '');
    } else if (existingRes.status !== 404) {
      console.warn(`[upgradeTemplate] failed to fetch band file ${file.path}: ${existingRes.status}`);
      continue;
    }

    // Skip if byte-identical (GitHub returns content with newlines; compare normalized).
    const normalizedTemplate = templateContent.replace(/\n/g, '');
    if (existingContent && existingContent === normalizedTemplate) {
      filesSkipped++;
      continue;
    }

    const putBody = {
      message: `Template upgrade: ${file.path}`,
      content: normalizedTemplate,
      ...(existingSha ? { sha: existingSha } : {}),
    };

    const putRes = await fetch(
      `https://api.github.com/repos/${owner}/${bandRepoName}/contents/${encodeURIComponent(file.path)}`,
      {
        method: 'PUT',
        headers: githubHeaders(),
        body: JSON.stringify(putBody),
      }
    );
    if (!putRes.ok) {
      const err = await putRes.json().catch(() => ({}));
      console.warn(`[upgradeTemplate] PUT failed for ${file.path}: ${err.message || putRes.statusText}`);
      continue;
    }

    if (existingSha) filesUpdated++;
    else filesCreated++;
  }

  return { filesUpdated, filesCreated, filesSkipped, totalConsidered: filesToCopy.length };
}

/**
 * Create a Vercel project linked to the GitHub repo.
 */
export async function createVercelProject(repoName, bandSlug) {
  const res = await fetch(`https://api.vercel.com/v10/projects${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify({
      name: `bandchat-${bandSlug}`,
      framework: 'vite',
      gitRepository: {
        type: 'github',
        repo: `${WEBSITE_GITHUB_ORG}/${repoName}`,
      },
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Vercel project creation failed: ${err.error?.message || res.statusText}`);
  }

  const project = await res.json();
  return project.id;
}

/**
 * Set environment variables on the Vercel project.
 */
export async function setVercelEnvVars(projectId, vars) {
  const envVars = Object.entries(vars).map(([key, value]) => ({
    key,
    value: String(value),
    target: ['production', 'preview'],
    type: 'encrypted',
  }));

  const res = await fetch(`https://api.vercel.com/v10/projects/${projectId}/env${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify(envVars),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Vercel env vars failed: ${err.error?.message || res.statusText}`);
  }
}

/**
 * Add a custom domain to the Vercel project.
 */
export async function addVercelDomain(projectId, domain) {
  const res = await fetch(`https://api.vercel.com/v10/projects/${projectId}/domains${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify({ name: domain }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Vercel domain failed: ${err.error?.message || res.statusText}`);
  }
}

/**
 * Create a deploy hook URL for the Vercel project (used for auto-rebuilds).
 */
export async function createDeployHook(projectId) {
  const res = await fetch(`https://api.vercel.com/v10/projects/${projectId}/deploy-hooks${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify({
      name: 'bandchat-sync',
      ref: 'main',
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Deploy hook creation failed: ${err.error?.message || res.statusText}`);
  }

  const data = await res.json();
  return data.url;
}

/**
 * Trigger a deploy via the deploy hook URL (fire-and-forget POST).
 */
export async function triggerDeploy(deployHookUrl) {
  if (!deployHookUrl) return;
  try {
    await fetch(deployHookUrl, { method: 'POST' });
  } catch {
    // Fire-and-forget — don't throw
    console.error('Website deploy hook trigger failed');
  }
}

/**
 * Create a production deployment directly via Vercel API.
 * Used for initial deploys where the deploy hook may not trigger.
 */
export async function createDeployment(projectId, repoName) {
  const res = await fetch(`https://api.vercel.com/v13/deployments${vercelTeamParam()}`, {
    method: 'POST',
    headers: vercelHeaders(),
    body: JSON.stringify({
      name: projectId,
      project: projectId,
      target: 'production',
      gitSource: {
        type: 'github',
        org: WEBSITE_GITHUB_ORG,
        repo: repoName,
        ref: 'main',
      },
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    console.error('Create deployment failed:', err);
    // Non-fatal — deploy hook or next commit will trigger it
  }
}

/**
 * Delete the Vercel project.
 */
export async function deleteVercelProject(projectId) {
  const res = await fetch(`https://api.vercel.com/v10/projects/${projectId}${vercelTeamParam()}`, {
    method: 'DELETE',
    headers: vercelHeaders(),
  });

  if (!res.ok && res.status !== 404) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Vercel project deletion failed: ${err.error?.message || res.statusText}`);
  }
}

/**
 * Delete the GitHub repo for this band's website.
 */
export async function deleteGithubRepo(repoName) {
  const res = await fetch(`https://api.github.com/repos/${WEBSITE_GITHUB_ORG}/${repoName}`, {
    method: 'DELETE',
    headers: githubHeaders(),
  });

  if (!res.ok && res.status !== 404) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`GitHub repo deletion failed: ${err.message || res.statusText}`);
  }
}

/**
 * Generate a scoped API token for the website to fetch band data.
 * Returns the plaintext token (stored hashed in DB).
 */
export async function generateApiToken(workspaceId) {
  const plaintext = crypto.randomBytes(32).toString('hex');
  const hashed = crypto.createHash('sha256').update(plaintext).digest('hex');

  // Delete any existing tokens for this workspace
  await prisma.websiteApiToken.deleteMany({ where: { workspaceId } });

  await prisma.websiteApiToken.create({
    data: {
      token: hashed,
      workspaceId,
    },
  });

  return plaintext;
}

/**
 * Verify a website API token. Returns workspaceId if valid, null otherwise.
 */
export async function verifyApiToken(plaintext) {
  if (!plaintext) return null;
  const hashed = crypto.createHash('sha256').update(plaintext).digest('hex');
  const record = await prisma.websiteApiToken.findUnique({ where: { token: hashed } });
  return record ? record.workspaceId : null;
}

/**
 * Debounce map: workspaceId → timeout handle.
 * Prevents deploy hook storms when many mutations happen in quick succession
 * (e.g. bulk song import). Waits 5 minutes after the last change before triggering.
 */
const SYNC_DEBOUNCE_MS = 5 * 60 * 1000; // 5 minutes
const syncTimers = new Map();

/**
 * Trigger a website rebuild if the workspace has a website enabled.
 * Debounced — waits 5 minutes after the last call before firing.
 * Fire-and-forget — safe to call from any route.
 */
export function triggerWebsiteSync(workspaceId) {
  // Clear any pending timer for this workspace
  const existing = syncTimers.get(workspaceId);
  if (existing) clearTimeout(existing);

  const timer = setTimeout(async () => {
    syncTimers.delete(workspaceId);
    try {
      const workspace = await prisma.workspace.findUnique({
        where: { id: workspaceId },
        select: { websiteEnabled: true, websiteDeployHook: true },
      });
      if (workspace?.websiteEnabled && workspace.websiteDeployHook) {
        triggerDeploy(workspace.websiteDeployHook);
      }
    } catch {
      // Best effort — don't crash
    }
  }, SYNC_DEBOUNCE_MS);

  syncTimers.set(workspaceId, timer);
}
